# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            云中红瞳的博客
tagline:          '想得多，做得少'
description:      '宅男一枚。主营前端，伪全栈，擅长 nodejs、graphql、react'
url:              https://xialvjun.github.io

author:
  name:           'xialvjun'
  url:            https://github.com/xialvjun

paginate:         5

# Custom vars
# version:          2.0.0

# github:
#   repo:           https://github.com/poole/lanyon
